# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cmz5SzQYihOGq5xPHvMJjzhjEmAn_zWG
"""

a=(9,)
print(type(a))

a=(9)
print(type(a))

a={"prem":20,"lohith":21}
print(a["prem"])