# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uxu26wWH1s_XxKPDB8axSVwN5YcLK6f9
"""

a='hello world'
b=a.upper()
c=a.replace('hello','hi')
d="123"
print(a)
print(b)
print(d)
print(d.isdigit())

a='hey mundaA'
print(a.swapcase())

a=range(5,20,5)
for i in a:
    print(i)

a=range(1,10,2)
print(list(a))

def prem(*args):
  return args
prem(1,2,3,4,5,6,7)

add=lambda x,y:x+y
add(2,3)

def signup():
  global a
  a=input("enter user name")
  global b
  b=input("passwaors")
def login():
  global c
  c=input("enter user name")
  global d
  d=input("passwaors")
  if a==c and b==d:
    print("login success")
  else:
    print("login failed")
signup()
login()